add_subdirectory(../../Submodules/freetype freetype)
add_subdirectory(../../CMake/Submodules/pthreads pthreads)
add_subdirectory(../../CMake/Submodules/zlib zlib)
add_subdirectory(../../CMake/Submodules/libpng libpng)

set_property(TARGET freetype PROPERTY FOLDER "Submodules")
set_property(TARGET pthreads PROPERTY FOLDER "Submodules")
set_property(TARGET zlib PROPERTY FOLDER "Submodules")
set_property(TARGET png_genfiles PROPERTY FOLDER "Submodules")
if(TARGET png_static)
    set_property(TARGET png_static PROPERTY FOLDER "Submodules")
endif()
if(TARGET png_shared)
    set_property(TARGET png_shared PROPERTY FOLDER "Submodules")
endif()
